title: Self Potrait
author: Yugesh Raut
email: yugeshraut.sae@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Hi this is Yugesh Raut..Welcome to my self-potrait..I am new to github ..

# social links
twitter_username: your-twitter-handle
github_username:  Yugesh37

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
